include "application"

gov_uk_notify {
  endpoint = "https://api.notifications.service.gov.uk"
  api_key = ${GOV_UK_NOTIFY_API_KEY}
  external_emails_on = false
  external_emails_on = ${?SEND_GOV_UK_NOTIFICATIONS}
  transfer_complete_dta_template_id = ${TRANSFER_COMPLETE_DTA_TEMPLATE_ID}
  transfer_complete_tb_template_id = ${TRANSFER_COMPLETE_TB_TEMPLATE_ID}
  metadata_review_requested_dta_template_id = ${METADATA_REVIEW_REQUESTED_DTA_TEMPLATE_ID}
  metadata_review_requested_tb_template_id = ${METADATA_REVIEW_REQUESTED_TB_TEMPLATE_ID}
  metadata_review_rejected_template_id = ${METADATA_REVIEW_REJECTED_TEMPLATE_ID}
  metadata_review_approved_template_id = ${METADATA_REVIEW_APPROVED_TEMPLATE_ID}
  upload_failed_template_id = ${UPLOAD_FAILED_TEMPLATE_ID}
  upload_complete_template_id = ${UPLOAD_COMPLETE_TEMPLATE_ID}
  file_check_failure_template_id = ${FILE_CHECK_FAILURE_TEMPLATE_ID}
}
